-- Decompiled with Potassium's decompiler.

return {
    humanoidAttachments = {
        RootRigAttachment = true,
        HatAttachment = true,
        HairAttachment = true,
        FaceFrontAttachment = true,
        FaceCenterAttachment = true,
        NeckRigAttachment = true,
        NeckRigAttachment = true,
        WaistRigAttachment = true,
        LeftCollarRigAttachment = true,
        RightCollarRigAttachment = true,
        BodyFrontAttachment = true,
        BodyBackAttachment = true,
        RootRigAttachment = true,
        WaistRigAttachment = true,
        WaistFrontAttachment = true,
        WaistCenterAttachment = true,
        WaistBackAttachment = true,
        LeftHipRigAttachment = true,
        RightHipRigAttachment = true,
        LeftShoulderRigAttachment = true,
        LeftElbowRigAttachment = true,
        LeftWristRigAttachment = true,
        LeftGripAttachment = true,
        LeftShoulderAttachment = true,
        RightShoulderRigAttachment = true,
        RightElbowRigAttachment = true,
        RightWristRigAttachment = true,
        RightGripAttachment = true,
        RightShoulderAttachment = true,
        LeftHipRigAttachment = true,
        LeftKneeRigAttachment = true,
        LeftAnkleRigAttachment = true,
        LeftFootAttachment = true,
        RightHipRigAttachment = true,
        RightKneeRigAttachment = true,
        RightAnkleRigAttachment = true,
        RightFootAttachment = true
    }
};