local v1 = {}
local v2 = setmetatable({}, {
    ["__index"] = v1
})
v2.DAMAGE = "DAMAGE"
v1.DAMAGE = "DAMAGE"
v2.ARMOR = "ARMOR"
v1.ARMOR = "ARMOR"
v2.TEAM_GENERATOR = "TEAM_GENERATOR"
v1.TEAM_GENERATOR = "TEAM_GENERATOR"
v2.DIAMOND_GENERATOR = "DIAMOND_GENERATOR"
v1.DIAMOND_GENERATOR = "DIAMOND_GENERATOR"
v2.BREAK_SPEED = "BREAK_SPEED"
v1.BREAK_SPEED = "BREAK_SPEED"
v2.SURVIVAL_BED_UPGRADE = "SURVIVAL_BED_UPGRADE"
v1.SURVIVAL_BED_UPGRADE = "SURVIVAL_BED_UPGRADE"
v2.SURVIVAL_PLUNDER_UPGRADE = "SURVIVAL_PLUNDER_UPGRADE"
v1.SURVIVAL_PLUNDER_UPGRADE = "SURVIVAL_PLUNDER_UPGRADE"
return {
    ["TeamUpgrade"] = v2
}