local v1 = {}
local v2 = setmetatable({}, {
    ["__index"] = v1
})
v2.LOCK_CAMERA = "lock_camaera"
v1.lock_camaera = "LOCK_CAMERA"
v2.MOBILE_SHIFT_LOCK = "mobileShiftLock"
v1.mobileShiftLock = "MOBILE_SHIFT_LOCK"
v2.BACKGROUND_MUSIC_VOLUME = "backgroundMusicVolume"
v1.backgroundMusicVolume = "BACKGROUND_MUSIC_VOLUME"
v2.BACKGROUND_MUSIC_VOLUME_GAME = "backgroundMusicVolumeGame"
v1.backgroundMusicVolumeGame = "BACKGROUND_MUSIC_VOLUME_GAME"
v2.FOV = "fov"
v1.fov = "FOV"
v2.PICTURE_MODE = "pictureMode"
v1.pictureMode = "PICTURE_MODE"
v2.FRIEND_NOTIFICATIONS = "friendNotifications"
v1.friendNotifications = "FRIEND_NOTIFICATIONS"
v2.FRIEND_SPECTATING = "friendSpectating"
v1.friendSpectating = "FRIEND_SPECTATING"
v2.STREAMER_MODE = "streamer_mode"
v1.streamer_mode = "STREAMER_MODE"
v2.CLAN_INVITES = "clan_invites"
v1.clan_invites = "CLAN_INVITES"
v2.MOBILE_PROJECTILE_BUTTON = "mobile_projectile_button"
v1.mobile_projectile_button = "MOBILE_PROJECTILE_BUTTON"
v2.MOBILE_BLOCK_BREAK_BUTTON = "mobile_block_break_button"
v1.mobile_block_break_button = "MOBILE_BLOCK_BREAK_BUTTON"
v2.MOBILE_INTERACT_BUTTON = "mobile_interact_button"
v1.mobile_interact_button = "MOBILE_INTERACT_BUTTON"
v2.MOBILE_AUTO_BRIDGE_BUTTON = "mobile_auto_bridge_button"
v1.mobile_auto_bridge_button = "MOBILE_AUTO_BRIDGE_BUTTON"
v2.GLOBAL_CHAT_SYSTEM_MESSAGES = "global_chat_system_messages"
v1.global_chat_system_messages = "GLOBAL_CHAT_SYSTEM_MESSAGES"
v2.PC_SHIFT_LOCK = "pc_shift_lock"
v1.pc_shift_lock = "PC_SHIFT_LOCK"
v2.ENABLE_AUTO_DEPOSIT = "enable_auto_deposit"
v1.enable_auto_deposit = "ENABLE_AUTO_DEPOSIT"
v2.EMOTE_VOLUME = "emote_volume"
v1.emote_volume = "EMOTE_VOLUME"
v2.SHOW_RESOURCES_IN_HUD = "show_resources_in_hud"
v1.show_resources_in_hud = "SHOW_RESOURCES_IN_HUD"
v2.ENABLE_ON_SCREEN_EFFECTS = "enable_on_screen_effects"
v1.enable_on_screen_effects = "ENABLE_ON_SCREEN_EFFECTS"
v2.PROFILE_VISIBILITY = "profile_visibility"
v1.profile_visibility = "PROFILE_VISIBILITY"
v2.SHOW_RECOMMENDED_SHOP = "show_recommended_shop"
v1.show_recommended_shop = "SHOW_RECOMMENDED_SHOP"
v2.SHOW_TIPS = "show_tips"
v1.show_tips = "SHOW_TIPS"
v2.MOBILE_SWORD_HOLD = "mobile_sword_hold"
v1.mobile_sword_hold = "MOBILE_SWORD_HOLD"
local v3 = {}
local v4 = setmetatable({}, {
    ["__index"] = v3
})
v4.GENERAL = "General"
v3.General = "GENERAL"
v4.MOBILE_CONTROLS = "Controls"
v3.Controls = "MOBILE_CONTROLS"
v4.KEYBINDS = "Keybinds"
v3.Keybinds = "KEYBINDS"
v4.PC = "PC Settings"
v3["PC Settings"] = "PC"
v4.MOBILE = "Mobile"
v3.Mobile = "MOBILE"
local v5 = {}
local v6 = setmetatable({}, {
    ["__index"] = v5
})
v6.AUDIO = "audio"
v5.audio = "AUDIO"
v6.GAME = "game"
v5.game = "GAME"
v6.FRIENDS = "friends"
v5.friends = "FRIENDS"
v6.PRIVACY = "privacy"
v5.privacy = "PRIVACY"
local v7 = {}
local v8 = setmetatable({}, {
    ["__index"] = v7
})
v8.TOGGLE = "toggle"
v7.toggle = "TOGGLE"
v8.SLIDER = "slider"
v7.slider = "SLIDER"
v8.CUSTOM = "custom"
v7.custom = "CUSTOM"
local v9 = {}
local v10 = setmetatable({}, {
    ["__index"] = v9
})
v10.PUBLIC = "public"
v9.public = "PUBLIC"
v10.FRIENDS_ONLY = "friends_only"
v9.friends_only = "FRIENDS_ONLY"
v10.PRIVATE = "private"
v9.private = "PRIVATE"
return {
    ["Setting"] = v2,
    ["SettingsTab"] = v4,
    ["SettingSection"] = v6,
    ["SettingInputType"] = v8,
    ["VisibilitySetting"] = v10
}