local v1 = {}
local v2 = setmetatable({}, {
    ["__index"] = v1
})
v2.ELECTRIC_WITH_ZAPPED_1 = 0
v1[0] = "ELECTRIC_WITH_ZAPPED_1"
v2.ELECTRIC_WITH_ZAPPED_2 = 1
v1[1] = "ELECTRIC_WITH_ZAPPED_2"
v2.ELECTRIC_WITH_ZAPPED_3 = 2
v1[2] = "ELECTRIC_WITH_ZAPPED_3"
v2.ELECTRIC_WITHOUT_ZAPPED = 3
v1[3] = "ELECTRIC_WITHOUT_ZAPPED"
v2.PROJECTILE = 4
v1[4] = "PROJECTILE"
v2.TRUE_DAMAGE = 5
v1[5] = "TRUE_DAMAGE"
v2.REPEATING = 6
v1[6] = "REPEATING"
v2.NO_APPLY_ENCHANT = 7
v1[7] = "NO_APPLY_ENCHANT"
return {
    ["DamageCategory"] = v2
}