local v1 = require(game:GetService("ReplicatedStorage"):WaitForChild("rbxts_include"):WaitForChild("RuntimeLib"))
local v2 = v1.import(script, game:GetService("ReplicatedStorage"), "rbxts_include", "node_modules", "@easy-games", "game-core", "out").GameCoreSharedSyncEvents
local v3 = v1.import(script, game:GetService("ReplicatedStorage"), "rbxts_include", "node_modules", "@easy-games", "sync-event", "out").SyncEvent
local v4 = v1.import(script, game:GetService("ReplicatedStorage"), "TS", "combat", "event", "hand-item-rendered-event").HandItemRenderedEvent
local v5 = v1.import(script, game:GetService("ReplicatedStorage"), "TS", "combat", "event", "sword-attack-event").SwordAttackEvent
local v6 = v1.import(script, game:GetService("ReplicatedStorage"), "TS", "combat", "event", "entity-equip-armor-visuals-event").EntityEquipArmorVisualsEvent
local v7 = v1.import(script, game:GetService("ReplicatedStorage"), "TS", "combat", "event", "grappling-hook", "hook-funciton-swap-event").HookFunctionSwapEvent
local v8 = v1.import(script, game:GetService("ReplicatedStorage"), "TS", "combat", "event", "projectile-expire-event").ProjectileExpiredEvent
local v9 = v1.import(script, game:GetService("ReplicatedStorage"), "TS", "combat", "event", "projectile-hit-event").ProjectileHitEvent
local v10 = v1.import(script, game:GetService("ReplicatedStorage"), "TS", "combat", "event", "projectile-render-event").ProjectileRenderEvent
local v11 = v1.import(script, game:GetService("ReplicatedStorage"), "TS", "combat", "event", "projectile-returned-event").ProjectileReturnedEvent
local v12 = v1.import(script, game:GetService("ReplicatedStorage"), "TS", "entity", "event", "shared-entity-damage-event").SharedEntityDamageEvent
local v13 = v1.import(script, game:GetService("ReplicatedStorage"), "TS", "entity", "event", "shared-entity-death-event").SharedEntityDeathEvent
local v14 = v1.import(script, game:GetService("ReplicatedStorage"), "TS", "games", "bedwars", "bed-plating", "bed-plate-destroyed-event").BedPlateDestroyedEvent
local v15 = v1.import(script, game:GetService("ReplicatedStorage"), "TS", "games", "overpowered", "overpowered-game-events")
local v16 = v15.AbilityCooldownModifierCheckEvent
local v17 = v15.AbilityTickDelayModifierCheckEvent
local v18 = v15.BuffDurationModifierCheckEvent
local v19 = v15.CastTimeModifierCheckEvent
local v20 = v15.ConsumableConsumeTimeModifierCheckEvent
local v21 = v15.CropGrowthTimeModifierCheckEvent
local v22 = v15.DebuffDurationModifierCheckEvent
local v23 = v15.ItemCooldownModifierCheckEvent
local v24 = v15.ResourceBuildingModifierCheckEvent
local v25 = v15.ProjectileCooldownModifierCheckEvent
local v26 = v15.ProjectileMaxChargeTimeModifierCheckEvent
local v27 = v15.RepeatingGiveItemModifierCheckEvent
local v28 = v15.ResourceSpawnDelayModifierCheckEvent
local v29 = v15.SwordChargeTimeModifierCheckEvent
local v30 = {}
for v31, v32 in v2 do
    v30[v31] = v32
end
v30.ProjectileRender = v3.new(v10)
v30.SwordChargedSwing = v3.new(v5)
v30.HookFunctionSwapEvent = v3.new(v7)
v30.ProjectileHit = v3.new(v9)
v30.HandItemRendered = v3.new(v4)
v30.SharedStatefulEntityDamage = v3.new(v12)
v30.SharedStatefulEntityDeath = v3.new(v13)
v30.BedPlatingDestroyed = v3.new(v14)
v30.ProjectileReturned = v3.new(v11)
v30.ProjectileExpired = v3.new(v8)
v30.EntityEquipArmorVisuals = v3.new(v6)
v30.ProjectileCooldownModifierCheck = v3.new(v25)
v30.ProjectileMaxChargeTimeModifierCheck = v3.new(v26)
v30.CropGrowthTimeModifierCheck = v3.new(v21)
v30.KitProgressModifierCheck = v3.new(v24)
v30.ItemCooldownModifierCheck = v3.new(v23)
v30.ResourceSpawnDelayModifierCheck = v3.new(v28)
v30.RepeatingGiveItemModifierCheck = v3.new(v27)
v30.AbilityCooldownModifierCheck = v3.new(v16)
v30.BuffDurationModifierCheck = v3.new(v18)
v30.DebuffDurationModifierCheck = v3.new(v22)
v30.CastTimeModifierCheck = v3.new(v19)
v30.AbilityTickDelayModifierCheck = v3.new(v17)
v30.ConsumableConsumeTimeModifierCheck = v3.new(v20)
v30.SwordChargeTimeModifierCheck = v3.new(v29)
return {
    ["SharedSyncEvents"] = v30
}