local u1 = setmetatable({}, {
    ["__tostring"] = function() --[[ Name: __tostring, Line 5 ]]
        return "HalloweenBalanceConfig"
    end
})
u1.__index = u1
function u1.new(...) --[[ Line: 10 ]]
    --[[
    Upvalues:
        [1] = u1
    --]]
    local v2 = u1
    local v3 = setmetatable({}, v2)
    return v3:constructor(...) or v3
end
function u1.constructor(_) --[[ Line: 14 ]] end
u1.MAX_HEALTH_INCREASE_FLAT = 10
u1.DAMAGE_INCREASE_PERCENT = 5
u1.SPEED_INCREASE_PERCENT = 5
u1.CRIT_CHANCE_INCREASE_PERCENT = 10
u1.PROJECTILE_ON_HIT_DMG_TIER_1_HALLOWEEN = 15
u1.PROJECTILE_ON_HIT_DMG_TIER_2_HALLOWEEN = 25
u1.PROJECTILE_ON_HIT_DMG_TIER_3_HALLOWEEN = 35
u1.DEATH_ADDER_HUGE_SHOT_DAMAGE_PERCENT = 100
u1.DEATH_ADDER_MULTI_SHOT_COUNT = 3
u1.DEATH_ADDER_DAMAGE_PERCENT = 20
u1.DEATH_ADDER_COOLDOWN_REDUCTION_PERCENT = 10
u1.DEATH_ADDER_BASE_COOLDOWN = 10
u1.DEATH_ADDER_CRITICAL_STRIKE_CHANCE = 10
u1.DEATH_ADDER_FRAG_NUMBER = 3
u1.SILAS_TRIUMPH_MAX_STACKS = 50
u1.SILAS_TRIUMPH_DAMAGE_REDUCTION_PER_STACK = 0.01
u1.SILAS_AURA_EFFECTIVENESS_PERCENT = 10
u1.SILAS_AURA_RADIUS_PERCENT = 20
u1.SILAS_TRIUMPH_STACK_MULTIPLIER = 2
u1.SILAS_HEX_DEBUFF_DURATION = 10
u1.SILAS_HEX_DEBUFF_PERCENT_PER_STACK = 2
u1.SILAS_LIFESTEAL_DURATION = 30
u1.SILAS_DAMAGE_DURATION = 30
u1.SILAS_DAMAGE_PERCENT_PER_STACK = 10
u1.KAIDA_COOLDOWN_REDUCTION_SECONDS = 2
u1.KAIDA_EXPANSION_PERCENT = 10
u1.KAIDA_UNIQUE_FIRE_DURATION = 10
u1.KAIDA_UNIQUE_FIRE_DAMAGE = 10
u1.KAIDA_UNIQUE_FIRE_DAMAGE_FREQUENCY = 1
u1.KAIDA_UNIQUE_LIFESTEAL_HEAL_PER_HIT = 15
u1.KAIDA_UNIQUE_KNOCKBACK_HORIZONTAL_MULTIPLIER = 10
u1.KAIDA_UNIQUE_KNOCKBACK_DAMAGE_PERCENT = 20
u1.NAZAR_KNOCKBACK_STRIKE_DAMAGE_PERCENT = 100
u1.NAZAR_KNOCKBACK_STRIKE_LIFE_FORCE_COST = 20
u1.NAZAR_KNOCKBACK_BUFF_DURATION = 7
u1.NAZAR_KNOCKBACK_SPEED_STUD_PER_SEC = 180
u1.NAZAR_KNOCKBACK_STUD_DISTANCE = 30
u1.NAZAR_KNOCKBACK_STRIKE_UPGRADED_DAMAGE_PERCENT = 60
u1.NAZAR_EMPOWERED_DAMAGE_PERCENT = 20
u1.NAZAR_LIFEFORCE_ON_HIT_PERCENT = 10
u1.NAZAR_STACKING_EMPOWERED_DURATION = 7
u1.NAZAR_STACKING_EMPOWERED_DAMAGE_PERCENT = 5
u1.NAZAR_LIFE_FORCE_SHIELD_THRESHOLD = 10
u1.NAZAR_LIFE_FORCE_PER_DAMAGE = 1
return {
    ["HalloweenBalanceConfig"] = u1
}