local v1 = {
    ["BASIC_STRIKE_BASE_DAMAGE"] = 48,
    ["ENHANCED_STRIKE_BASE_DAMAGE"] = 58,
    ["RAPIER_ATTACK_COOLDOWN"] = 0.5,
    ["CRIT_STRIKE_MULTIPLIER"] = 1.5,
    ["HERO_MIN_PERCENT_HEALTH_TO_CRIT"] = 0.6,
    ["VILLAIN_MAX_PERCENT_HEALTH_TO_CRIT"] = 0.4,
    ["ENHANCED_STRIKE_CONE_DISTANCE"] = 25,
    ["PROJECTILE_DAMAGE"] = 25,
    ["PROJECTILE_VELOCITY_MULTIPLIER"] = 600,
    ["PROJECTILE_DELAY"] = 0.2
}
local v2 = {}
local v3 = setmetatable({}, {
    ["__index"] = v2
})
v3.BASE = 0
v2[0] = "BASE"
v3.ADDITIONAL_PROJECTILES1 = 1
v2[1] = "ADDITIONAL_PROJECTILES1"
v3.CRITICAL_PROJECTILES = 2
v2[2] = "CRITICAL_PROJECTILES"
v3.ADDITIONAL_PROJECTILES2 = 3
v2[3] = "ADDITIONAL_PROJECTILES2"
v1.RAPIER_TIERS = v3
v1.NUM_PROJECTILES_MAP = {
    [v3.BASE] = 1,
    [v3.ADDITIONAL_PROJECTILES1] = 3,
    [v3.CRITICAL_PROJECTILES] = 3,
    [v3.ADDITIONAL_PROJECTILES2] = 5
}
return {
    ["MagicalGirlRapierBalance"] = v1
}