local v1 = {
    ["SOLAR_FLARE_DURATION"] = 10,
    ["SOLAR_FLARE_EXPLOSION_PROC_STACK_REQ"] = 3,
    ["SOLAR_FLARE_AFTERSHOCK_DAMAGE"] = 5,
    ["SOLAR_FLARE_AFTERSHOCK_DELAY"] = 1,
    ["SOLAR_FLARE_AFTERSHOCK_PROC_STACK_INTERVAL"] = 0.1,
    ["LUNAR_VENOM_DURATION"] = 5,
    ["LUNAR_VENOM_INFECTION_PROC_STACK_REQ"] = 3,
    ["LUNAR_VENOM_TICK_INTERVAL"] = 1,
    ["LUNAR_VENOM_BASE_DAMAGE"] = 1,
    ["LUNAR_VENOM_INFECTION_PROC_DAMAGE"] = 20,
    ["NUM_BASE_PROJECTILES"] = 2,
    ["NUM_EXTRA_PROJECTILES_1"] = 1,
    ["NUM_EXTRA_PROJECTILES_2"] = 3,
    ["MULTI_SHOT_CHARGE_TIME"] = 0.5
}
local v2 = {}
local v3 = setmetatable({}, {
    ["__index"] = v2
})
v3.BASE = 0
v2[0] = "BASE"
v3.EXTRA_PROJECTILES_1 = 1
v2[1] = "EXTRA_PROJECTILES_1"
v3.STACKING_EFFECTS = 2
v2[2] = "STACKING_EFFECTS"
v3.EXTRA_PROJECTILES_2 = 3
v2[3] = "EXTRA_PROJECTILES_2"
v1.TIERS = v3
return {
    ["MagicalGirlScepterUtil"] = v1
}