local v1 = require(game:GetService("ReplicatedStorage"):WaitForChild("rbxts_include"):WaitForChild("RuntimeLib"))
local v2 = v1.import(script, game:GetService("ReplicatedStorage"), "rbxts_include", "node_modules", "@easy-games", "block-engine", "out", "client", "block-engine-client-events").BlockEngineClientEvents
local v3 = v1.import(script, game:GetService("ReplicatedStorage"), "rbxts_include", "node_modules", "@easy-games", "game-core", "out").GameCoreClientSyncEvents
local v4 = v1.import(script, game:GetService("ReplicatedStorage"), "rbxts_include", "node_modules", "@easy-games", "sync-event", "out").SyncEvent
local v5 = v1.import(script, game:GetService("ReplicatedStorage"), "TS", "combat", "event", "first-person-item-rendered-event").FirstPersonItemRendered
local v6 = v1.import(script, game:GetService("ReplicatedStorage"), "TS", "disaster", "disaster-events").DisasterBeganEvent
local v7 = v1.import(script, game:GetService("ReplicatedStorage"), "TS", "shared-sync-events").SharedSyncEvents
local v8 = v1.import(script, script.Parent, "controllers", "game", "block", "events", "ground-touch-event").GroundTouchEvent
local v9 = v1.import(script, script.Parent, "controllers", "game", "block", "launch-pad", "event", "launch-pad-used-event").LaunchPadUsedEvent
local v10 = v1.import(script, script.Parent, "controllers", "game", "combat", "event", "perform-combat-event").PerformCombatEvent
local v11 = v1.import(script, script.Parent, "controllers", "game", "combat", "explosion", "explosion-sync-events").ExplosionEffectEvent
local v12 = v1.import(script, script.Parent, "controllers", "game", "combat", "projectile", "event", "begin-projectile-targeting-event").BeginProjectileTargetingEvent
local v13 = v1.import(script, script.Parent, "controllers", "game", "combat", "projectile", "event", "fire-client-projectile-event").FireClientProjectileEvent
local v14 = v1.import(script, script.Parent, "controllers", "game", "combat", "projectile", "event", "projectile-destroy-event").ProjectileDestroyEvent
local v15 = v1.import(script, script.Parent, "controllers", "game", "combat", "projectile", "event", "projectile-launched-event").ProjectileLaunchedEvent
local v16 = v1.import(script, script.Parent, "controllers", "game", "combat", "projectile", "event", "projectile-max-charged-event").ProjectileMaxChargedEvent
local v17 = v1.import(script, script.Parent, "controllers", "game", "combat", "projectile", "event", "projectile-targeting-ended-event").ProjectileTargetingEndedEvent
local v18 = v1.import(script, script.Parent, "controllers", "game", "combat", "projectile", "event", "start-projectile-launch-event").StartProjectileLaunchEvent
local v19 = v1.import(script, script.Parent, "controllers", "game", "combat", "projectile", "guided-projectile", "event", "guided-projectile-events")
local v20 = v19.GuidedProjectileDetonateEvent
local v21 = v19.GuidedProjectileDisablingEvent
local v22 = v19.GuidedProjectileEnablingEvent
local v23 = v19.GuidedProjectileRemovedEvent
local v24 = v1.import(script, script.Parent, "controllers", "game", "enchant-table", "event", "start-enchant-repair-event").StartEnchantRepairEvent
local v25 = v1.import(script, script.Parent, "controllers", "game", "items", "double-rainbow-boots.ts", "rainbow-boots-equipped-event").RainbowBootsEquippedEvent
local v26 = v1.import(script, script.Parent, "controllers", "game", "items", "drill", "event", "switch-drill-event").SwitchDrillEvent
local v27 = v1.import(script, script.Parent, "controllers", "game", "items", "owl", "events", "new-owl-target-sync-event").NewOwlTargetEvent
local v28 = v1.import(script, script.Parent, "controllers", "game", "items", "zipline", "event", "zipline-mount-event").ZiplineMountEvent
local v29 = v1.import(script, script.Parent, "controllers", "game", "kit", "kit-equip-event").ClientKitEquipEvent
local v30 = v1.import(script, script.Parent, "controllers", "game", "kit", "kit-unequip-event").ClientKitUnequipEvent
local v31 = v1.import(script, script.Parent, "controllers", "game", "match-end", "events", "match-end-screen-end-event").MatchEndScreenEndEvent
local v32 = v1.import(script, script.Parent, "controllers", "game", "match-end", "events", "match-end-screen-start-event").MatchEndScreenStartEvent
local v33 = v1.import(script, script.Parent, "controllers", "game", "movement", "event", "move-mount-event").MoveMountEvent
local v34 = v1.import(script, script.Parent, "controllers", "game", "scene", "event", "scene-loading-screen-end-event").SceneLoadingScreenEndEvent
local v35 = v1.import(script, script.Parent, "controllers", "game", "scene", "event", "scene-loading-screen-end-event copy").SceneLoadingScreenStartEvent
local v36 = v1.import(script, script.Parent, "controllers", "game", "scene", "event", "scene-started-event").SceneStartedEvent
local v37 = v1.import(script, script.Parent, "controllers", "game", "score", "event", "point-captured-event").PointCapturedEvent
local v38 = v1.import(script, script.Parent, "controllers", "game", "score", "event", "point-setup-event").PointSetupEvent
local v39 = v1.import(script, script.Parent, "controllers", "game", "score", "event", "team-score-change-event").TeamScoreChangeEvent
local v40 = v1.import(script, script.Parent, "controllers", "game", "status-effect", "event", "client-status-effect-added-event").ClientStatusEffectAddedEvent
local v41 = v1.import(script, script.Parent, "controllers", "game", "status-effect", "event", "client-status-effect-reapplied-event").ClientStatusEffectReappliedEvent
local v42 = v1.import(script, script.Parent, "controllers", "game", "status-effect", "event", "client-status-effect-removed-event").ClientStatusEffectRemovedEvent
local v43 = v1.import(script, script.Parent, "controllers", "game", "target-selector", "change-target-sync-event").NewSelectorTargetEvent
local v44 = v1.import(script, script.Parent, "controllers", "game", "team-buff", "event", "team-buff-applied-event").TeamBuffAppliedEvent
local v45 = v1.import(script, script.Parent, "controllers", "game", "visualizer", "event", "hit-effect-visualized-event").HitEffectVisualizedEvent
local v46 = v1.import(script, script.Parent, "controllers", "game", "visualizer", "event", "projectile-effect-visualized-event").ProjectileEffectVisualizedEvent
local v47 = v1.import(script, script.Parent, "controllers", "game", "visualizer", "event", "weapon-effect-visualized-event").WeaponEffectVisualizedEvent
local v48 = v1.import(script, script.Parent, "controllers", "game", "world", "event", "world-change-event").WorldChangeEvent
local v49 = v1.import(script, script.Parent, "controllers", "games", "bedwars", "bed", "events", "bed-health-changed-event").BedDamagedEvent
local v50 = v1.import(script, script.Parent, "controllers", "games", "bedwars", "collectable-entity", "collect-entity-event").CollectEntityEvent
local v51 = v1.import(script, script.Parent, "controllers", "games", "bedwars", "fisherman", "fisherman-minigame-end-event").FishermanMinigameEndEvent
local v52 = v1.import(script, script.Parent, "controllers", "games", "bedwars", "kit", "kits", "wind-walker", "event", "wind-walker-orb-update-event").WindWalkerOrbUpdateEvent
local v53 = v1.import(script, script.Parent, "controllers", "games", "bedwars", "team-upgrade", "team-upgrade-opened-event").TeamUpgradeOpenedEvent
local v54 = v1.import(script, script.Parent, "controllers", "games", "bedwars", "traveling-merchant", "event", "traveling-merchant-billboard-mounted-event").TravelingMerchantBillboardMountedEvent
local v55 = v1.import(script, script.Parent, "controllers", "games", "pvp-arena", "event", "pvp-arena-augment-selected-event").PvPArenaAugmentClientSelectedEvent
local v56 = v1.import(script, script.Parent, "controllers", "global", "background-music", "events", "background-music-started-event").BackgroundMusicStartedEvent
local v57 = v1.import(script, script.Parent, "controllers", "global", "background-music", "events", "background-music-stopped-event").BackgroundMusicStoppedEvent
local v58 = v1.import(script, script.Parent, "controllers", "global", "backpack", "backpack-equip-event").BackpackEquipEvent
local v59 = v1.import(script, script.Parent, "controllers", "global", "combat", "projectile", "event", "local-projectile-impact-event").LocalProjectileImpactEvent
local v60 = v1.import(script, script.Parent, "controllers", "global", "combat", "sword", "before-sword-swing-event").BeforeSwordSwingEvent
local v61 = v1.import(script, script.Parent, "controllers", "global", "combat", "sword", "event", "mobile-sword-button-pressed-event").MobileSwordButtonPressedEvent
local v62 = v1.import(script, script.Parent, "controllers", "global", "combat", "sword", "event", "sword-charge-event").SwordChargeEvent
local v63 = v1.import(script, script.Parent, "controllers", "global", "combat", "sword", "event", "sword-press-events")
local v64 = v63.SwordPressDownEvent
local v65 = v63.SwordPressUpEvent
local v66 = v1.import(script, script.Parent, "controllers", "global", "combat", "sword", "event", "sword-swing-event").SwordSwingEvent
local v67 = v1.import(script, script.Parent, "controllers", "global", "connect", "event", "match-state-change-event").MatchStateChangeEvent
local v68 = v1.import(script, script.Parent, "controllers", "global", "consume", "event", "item-consumed-event").ItemConsumedEvent
local v69 = v1.import(script, script.Parent, "controllers", "global", "consume", "event", "start-consuming-event").StartConsumingEvent
local v70 = v1.import(script, script.Parent, "controllers", "global", "consume", "event", "stop-consuming-event").StopConsumingEvent
local v71 = v1.import(script, script.Parent, "controllers", "global", "controls", "event", "shift-lock-toggle-event").ShiftLockToggleEvent
local v72 = v1.import(script, script.Parent, "controllers", "global", "daily-weekly", "events", "daily-reset-event").DailyResetEvent
local v73 = v1.import(script, script.Parent, "controllers", "global", "inventory", "event", "entity-change-armor-slot-event").EntityChangeArmorSlotEvent
local v74 = v1.import(script, script.Parent, "controllers", "global", "inventory", "event", "item-added-event").ItemAddedEvent
local v75 = v1.import(script, script.Parent, "controllers", "global", "inventory", "event", "item-hold-event").ItemHoldEvent
local v76 = v1.import(script, script.Parent, "controllers", "global", "inventory", "event", "item-remove-event").ItemRemovedEvent
local v77 = v1.import(script, script.Parent, "controllers", "global", "inventory", "event", "new-hand-item-event").NewHandItemEvent
local v78 = v1.import(script, script.Parent, "controllers", "global", "item-durability", "event", "client-item-durability-broken-client-event").ClientItemDurabilityBrokenEvent
local v79 = v1.import(script, script.Parent, "controllers", "global", "item-durability", "event", "client-item-durability-changed-client-event").ClientItemDurabilityChangedEvent
local v80 = v1.import(script, script.Parent, "controllers", "global", "locker", "break-bed-effect", "start-bed-break-effect-preview-event").StartBedBreakEffectPreview
local v81 = v1.import(script, script.Parent, "controllers", "global", "locker", "emote", "event", "cancel-emote-event").CancelEmoteClientEvent
local v82 = v1.import(script, script.Parent, "controllers", "global", "locker", "kill-effect", "kill-effect-event").KillEffectEvent
local v83 = v1.import(script, script.Parent, "controllers", "global", "mount", "mount-events")
local v84 = v83.GenericMountDismounted
local v85 = v83.GenericMountMounted
local v86 = v1.import(script, script.Parent, "controllers", "global", "settings", "event", "setting-changed-event").SettingChangedEvent
local v87 = v1.import(script, script.Parent, "controllers", "global", "ui", "ui-alert", "event", "new-ui-alert-event").NewUIAlertEvent
local v88 = v1.import(script, script.Parent, "controllers", "global", "viewmodel", "event", "view-model-item-added-event").ViewModelItemAddedEvent
local v89 = v1.import(script, script.Parent, "controllers", "lobby", "clan", "events", "clan-leave-event").ClanLeaveEvent
local v90 = v1.import(script, script.Parent, "controllers", "lobby", "clan", "events", "clan-update-event").ClanUpdateEvent
local v91 = v1.import(script, script.Parent, "controllers", "lobby", "locker", "event", "locker-preview-ended-event").LockerPreviewEndedEvent
local v92 = v1.import(script, script.Parent, "controllers", "lobby", "locker", "event", "locker-preview-started-event").LockerPreviewStartedEvent
local v93 = v1.import(script, script.Parent, "controllers", "games", "bedwars", "kit", "kits", "eldertree", "orb-collect-event").ElderTreeCollectEvent
local v94 = {}
for v95, v96 in v7 do
    v94[v95] = v96
end
for v97, v98 in v3 do
    v94[v97] = v98
end
for v99, v100 in v2 do
    v94[v99] = v100
end
v94.GroundTouch = v4.new(v8)
v94.SwordSwing = v4.new(v66)
v94.SwordCharge = v4.new(v62)
v94.SwordSwingDown = v4.new(v64)
v94.SwordSwingUp = v4.new(v65)
v94.BeforeSwordSwing = v4.new(v60)
v94.PerformCombat = v4.new(v10)
v94.BeginProjectileTargeting = v4.new(v12)
v94.ProjectileTargetingEnded = v4.new(v17)
v94.FireClientProjectile = v4.new(v13)
v94.StartLaunchProjectile = v4.new(v18)
v94.ProjectileLaunched = v4.new(v15)
v94.ProjectileDestroy = v4.new(v14)
v94.ProjectileMaxCharged = v4.new(v16)
v94.LocalProjectileImpact = v4.new(v59)
v94.FishermanMinigameEnd = v4.new(v51)
v94.MatchEndScreenStart = v4.new(v32)
v94.MatchEndScreenEnd = v4.new(v31)
v94.WindWalkerOrbUpdate = v4.new(v52)
v94.ElderTreeCollect = v4.new(v93)
v94.OwlNewTarget = v4.new(v27)
v94.GuidedProjectileDetonated = v4.new(v20)
v94.GuidedProjectileRemoved = v4.new(v23)
v94.GuidedProjectileDisabling = v4.new(v21)
v94.GuidedProjectileEnabling = v4.new(v22)
v94.StatusEffectAdded = v4.new(v40)
v94.StatusEffectChanged = v4.new(v40)
v94.StatusEffectRemoved = v4.new(v42)
v94.StatusEffectReapplied = v4.new(v41)
v94.LaunchPadUsed = v4.new(v9)
v94.KitEquip = v4.new(v29)
v94.KitUnequip = v4.new(v30)
v94.KillEffect = v4.new(v82)
v94.ViewModelItemAdded = v4.new(v88)
v94.DisasterBegan = v4.new(v6)
v94.ItemAdded = v4.new(v74)
v94.ItemRemoved = v4.new(v76)
v94.MobileSwordButtonPressed = v4.new(v61)
v94.CancelEmoteEvent = v4.new(v81)
v94.ExplosionEffect = v4.new(v11)
v94.GenericMountMounted = v4.new(v85)
v94.GenericMountDismounted = v4.new(v84)
v94.ZiplineMount = v4.new(v28)
v94.ChangeWorld = v4.new(v48)
v94.EntityChangeHeldItem = v4.new(v75)
v94.EntityChangeArmorSlotItem = v4.new(v73)
v94.BackpackEquipEvent = v4.new(v58)
v94.ItemConsumed = v4.new(v68)
v94.StartConsuming = v4.new(v69)
v94.StopConsuming = v4.new(v70)
v94.StartEnchantRepair = v4.new(v24)
v94.MatchStateChange = v4.new(v67)
v94.NewHandItem = v4.new(v77)
v94.SceneStarted = v4.new(v36)
v94.SceneLoadingScreenStart = v4.new(v35)
v94.SceneLoadingScreenEnd = v4.new(v34)
v94.CollectEntity = v4.new(v50)
v94.SettingChanged = v4.new(v86)
v94.ProjectileEffectVisualized = v4.new(v46)
v94.WeaponEffectVisualized = v4.new(v47)
v94.HitEffectVisualized = v4.new(v45)
v94.RainbowBootsEquipped = v4.new(v25)
v94.SwitchDrill = v4.new(v26)
v94.TravelingMerchantBillboardMounted = v4.new(v54)
v94.NewSelectorTarget = v4.new(v43)
v94.TeamScoreChange = v4.new(v39)
v94.PointCaptured = v4.new(v37)
v94.PointSetup = v4.new(v38)
v94.FirstPersonItemRendered = v4.new(v5)
v94.TeamUpgradeOpened = v4.new(v53)
v94.MoveMountButtonChange = v4.new(v33)
v94.PvPArenaAugmentClientSelected = v4.new(v55)
v94.ItemDurabilityChanged = v4.new(v79)
v94.ItemDurabilityBroken = v4.new(v78)
v94.TeamBuffApplied = v4.new(v44)
v94.ClanLeave = v4.new(v89)
v94.ClanUpdate = v4.new(v90)
v94.NewUIAlert = v4.new(v87)
v94.BedDamaged = v4.new(v49)
v94.DailyReset = v4.new(v72)
v94.StartBedBreakEffectPreview = v4.new(v80)
v94.LockerPreviewStarted = v4.new(v92)
v94.LockerPreviewEnded = v4.new(v91)
v94.BackgroundMusicStarted = v4.new(v56)
v94.BackgroundMusicStopped = v4.new(v57)
v94.ShiftLockToggle = v4.new(v71)
return {
    ["ClientSyncEvents"] = v94
}